from __future__ import annotations

import argparse
import traceback

from core import state_engine as runtime
from utils.logger import configure_logging, emit, log_run_header


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--states", default="states.json", help="Input states.json path")
    parser.add_argument("--config", default="config.json", help="External config JSON path")
    parser.add_argument("--trades-file", default="trades.json", help="External trades JSON path")
    parser.add_argument("--csv-dir", default="./data", help="Directory containing CSV files")
    parser.add_argument("--allow-incomplete-csv-rows", action="store_true", help="Bypass incomplete OHLC rows by skipping them instead of failing")
    parser.add_argument("--tickers", default="", help="Comma-separated tickers override")
    parser.add_argument("--out", default="", help="Output path (default: <states_stem>.updated.json)")
    parser.add_argument("--keep-history-rows", type=int, default=0, help="Override history rows to keep (0 = automatic)")
    parser.add_argument("--derive-signals-inputs", choices=["missing", "force", "never"], default="missing")
    parser.add_argument("--derive-threshold-inputs", choices=["missing", "force", "never"], default="missing")
    parser.add_argument("--prices-now-from", choices=["close", "never"], default="close")
    parser.add_argument("--mode", default="", help="Mode for report-scoped updates, such as Premarket, Intraday, or AfterClose")
    parser.add_argument("--now-et", default="", help="Override current ET datetime for report-context resolution")
    parser.add_argument("-f", "--force-mode", action="store_true", help="Bypass the ET/session check and run the requested --mode anyway")
    parser.add_argument("--render-report", action="store_true", help="Render the markdown report after state updates complete")
    parser.add_argument("--report-schema", default="report_spec.json", help="Schema path used when --render-report is enabled")
    parser.add_argument("--report-dir", default="report", help="Output directory for generated reports")
    parser.add_argument("--report-json-out", default="", help="Explicit JSON snapshot output path for mode-based report snapshots")
    parser.add_argument("--report-out", default="", help="Explicit report output path")
    parser.add_argument("--log-file", default="", help="Optional run log path")
    parser.add_argument("--broker-investment-total-usd", type=float, default=None, help="Broker investment total excluding cash, in USD")
    parser.add_argument("--broker-investment-total-kind", choices=["market_value", "cost_basis"], default="cost_basis", help="Interpretation of broker investment total")
    parser.add_argument("--tactical-cash-usd", type=float, default=None, help="Tactical cash balance excluding holdings, in USD")
    parser.add_argument("--initial-investment-usd", type=float, default=None, help="Persistent initial investment amount in USD")
    parser.add_argument("--cash-adjust-usd", type=float, default=None, help="External cash adjustment in USD")
    parser.add_argument("--cash-adjust-note", default="", help="Optional note for external cash adjustments")
    parser.add_argument("--cash-transfer-to-reserve-usd", type=float, default=None, help="Internal transfer between deployable and reserve cash buckets")
    parser.add_argument("--broker-asof-et", default="", help="Semantic broker as-of trade day in ET")
    parser.add_argument("--broker-asof-et-time", default="", help="Optional broker time component in ET")
    parser.add_argument("--broker-asof-et-datetime", default="", help="Optional broker datetime component in ET")
    parser.add_argument("--imported-trades-json", action="append", default=[], help="Repeatable path to normalized trades JSON generated by an external importer")
    parser.add_argument("--trades-import-mode", choices=["append", "replace"], default="append", help="How to merge imported trades into states.trades")
    parser.add_argument("--verify-tolerance-usd", type=float, default=1.0, help="Tolerance in USD for broker verification")
    args = parser.parse_args()

    logger, log_path = configure_logging("update_states", args.log_file)
    runtime.print = lambda *parts, **kwargs: emit(logger, *parts, **kwargs)
    logger.info(f"[LOG] file={log_path}")
    log_run_header(logger, "update_states.py", args)

    try:
        exit_code = int(runtime._run_main(args) or 0)
        logger.info(f"[EXIT] code={exit_code}")
    except SystemExit as exc:
        try:
            exit_code = int(exc.code) if exc.code is not None else 0
        except Exception:
            exit_code = 1
        logger.info(f"[EXIT] code={exit_code}")
        raise
    except Exception:
        logger.error("[EXCEPTION] uncaught exception follows")
        traceback.print_exc()
        logger.error("[EXIT] code=1")
        raise
    finally:
        logger.info(f"[LOG] complete file={log_path}")


if __name__ == "__main__":
    main()
